ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

#
# This works around an optimizer bug in the (Patch B) compiler
# This should be fixed in QNX 6.1
#
	CCFLAGS_a29f004_sync_sh += -O0
	CCFLAGS_aCFI_ident_sh += -O0
	CCFLAGS_iCFI_ident_sh += -O0

	CCFLAGS += $(CCF_$(COMPILER_TYPE)_$(COMPILER_DRIVER)) \
	        $(CCFLAGS_$(SECTION))   \
	        $(CCFLAGS_$(COMPILER_TYPE)_$(CPU)) \
	        $(CCFLAGS_$(CPU))   \
	        $(CCFLAGS_$(basename $@)) \
	        $(CCFLAGS_$(basename $@)_$(CPU))\
	        -DF3S_VER=3

ROOT_PATTERNS := $(dir $(wildcard ../../*/.))
CPU_PATTERNS := $(dir $(wildcard ../../*/Makefile))

EXTRA_SRCVPATH = $(filter-out $(CPU_PATTERNS), $(ROOT_PATTERNS))

NAME=mtd-flash

include $(MKFILES_ROOT)/qmacros.mk

# If the flash filesystem headers/libraries aren't present on the system, kill
# the compiles.
ifeq ($(call FIND_HDR_DIR,nto,usr/include,fs/f3s_spec.h),)
TARGET_BUILD=@$(ECHO_HOST) Flash filesystem headers/libraries not present on system	
TARGET_INSTALL=
SRCS=
endif


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

-include $(PROJECT_ROOT)/roots.mk

