EXTRA_SRCVPATH += $(PROJECT_ROOT)/sdmmc
EXTRA_SRCVPATH += $(PROJECT_ROOT)/fs
EXTRA_SRCVPATH += $(PROJECT_ROOT)/i2c
EXTRA_SRCVPATH += $(PROJECT_ROOT)/omap
EXTRA_SRCVPATH += $(PROJECT_ROOT)/nor
EXTRA_SRCVPATH += $(PROJECT_ROOT)/norspi
EXTRA_INCVPATH += $(PROJECT_ROOT)/private
