FROM ubuntu:25.04 AS build
COPY scripts/build-toolchain.sh configs/mips64el-linux-gnu.config /src/
RUN /src/build-toolchain.sh

FROM ubuntu:25.04
COPY --from=build /opt /opt
ENV XTOOLS_HOST="mips64el-linux-gnu"
ENV \
	PATH="/opt/x-tools/$XTOOLS_HOST/bin:$PATH" \
	PKG_CONFIG_PATH="/opt/x-tools/$XTOOLS_HOST/$XTOOLS_HOST/sysroot/usr/lib/pkgconfig"
COPY scripts/install-packages.sh /tmp
RUN /tmp/install-packages.sh qemu-user
